import BootstrapJs from "@/components/BotstrapJs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" --bs-body-color">
        <main className="container">
          <Navbar />
          {children}
        </main>
      </body>
      <BootstrapJs />
    </html>
  );
}
